(define (make-point x y) (cons x y))
(define (x-point p) (car p))
(define (y-point p) (cdr p))
(define (equal-point? p1 p2)
  (and (= (x-point p1) (x-point p2))
       (= (y-point p1) (y-point p2))))
(define (print-point p)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define (make-segment p q)
  (if (equal-point? p q)
      (error "same points don't define segment")
      (cons p q)))
(define (start-segment p) (car p))
(define (end-segment p) (cdr p))
(define (print-segment seg)
  (display "(")
  (print-point (start-segment seg))
  (display " -> ")
  (print-point (end-segment seg))
  (display ")"))

(define (midpoint-segment seg)
  (make-point (average (x-point (start-segment seg)) (x-point (end-segment seg)))
              (average (y-point (start-segment seg)) (y-point (end-segment seg)))))
